version: '3.8'

services:
  master:
    build:
      context: ./backend/master
    environment:
      NODE_NAME: master
      PORT: 8081
      SLAVE1: slave1:8082
      SLAVE2: slave2:8083
      SLAVE3: slave3:8084
    depends_on:
      - slave1
      - slave2
      - slave3
    networks:
      - app

  slave1:
    build:
      context: ./backend/slave
    environment:
      NODE_NAME: slave1
      PORT: 8082
    networks:
      - app

  slave2:
    build:
      context: ./backend/slave
    environment:
      NODE_NAME: slave2
      PORT: 8083
    networks:
      - app

  slave3:
    build:
      context: ./backend/slave
    environment:
      NODE_NAME: slave3
      PORT: 8084
    networks:
      - app

  api:
    build:
      context: ./backend/api
    environment:
      MASTER_NODE: master:8081
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - master
    networks:
      - app

  app:
    build:
      context: ./app
    environment:
      VITE_API_URL: http://api:3000/api
      VITE_API_WS: http://api:3000/ws
      VITE_API_TMDB: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2MWI5NzEyMWIzZTY1MTI3N2JiMTkzOWEyZGI2M2VkMyIsIm5iZiI6MTczMDYwOTI2OS43OTA3MTcsInN1YiI6IjY0YTcwNzE5OTU3ZTZkMDEzOWNmMDc2ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AvK5oxP2qIFQ4BbNpOsIR-Sj1bAZoqDx_VZPTY1Lx0w
    ports:
      - "4321:4321"
    depends_on:
      - api
    networks:
      - app

networks:
  app:
    driver: bridge


