services:
    # <--------------- NODOS
    # NODO SERVIDOR
    master:
        build:
            context: ./backend/master
            dockerfile: Dockerfile
        environment:
            - NODE_NAME=master
            - PORT=8081
            - SLAVE1=slave1:8082
            - SLAVE2=slave2:8083
            - SLAVE3=slave3:8084
        ports:
            - "8081:8081"
        networks:
            - slave_network
            - app
        depends_on:
            - slave1
            - slave2
            - slave3
    # NODOS CLIENTES
    slave1:
        build:
            context: ./backend/slave
            dockerfile: Dockerfile
        environment:
            - NODE_NAME=slave1
            - PORT=8082
        ports:
            - "8082:8082"
        networks:
            - slave_network

    slave2:
        build:
            context: ./backend/slave
            dockerfile: Dockerfile
        environment:
            - NODE_NAME=slave2
            - PORT=8083
        ports:
            - "8083:8083"
        networks:
            - slave_network

    slave3:
        build:
            context: ./backend/slave
            dockerfile: Dockerfile
        environment:
            - NODE_NAME=slave3
            - PORT=8084
        ports:
            - "8084:8084"
        networks:
            - slave_network

    # API ENDPOINT (BACKEND)
    api:
        build:
            context: ./backend/api
            dockerfile: Dockerfile
        environment:
            - MASTER_NODE=master:8081
            - PORT=3000
        ports:
            - "3000:3000"
        networks:
            - app
        depends_on:
            - master

    # App Web (FRONTEND)
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        environment:
            - VITE_API_URL=http://127.0.0.1:3000/api
            - VITE_API_TMDB=--YOUR-API-KEY--
        ports:
            - "4321:4321"
        networks:
            - app
        depends_on:
            - api

networks:
    slave_network:
    app:
